//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class abuthpaymentitem
    {
        public long Id { get; set; }
        public string ItemId { get; set; }
        public string TransId { get; set; }
        public string ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string DepartmentId { get; set; }
        public decimal Amount { get; set; }
        public string Quantity { get; set; }
        public System.DateTime Create_At { get; set; }
        public string offlineTransId { get; set; }
    }
}
