//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public string Agent_ID { get; set; }
        public string AgentName { get; set; }
        public Nullable<decimal> CollectLimit { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string MDA_ID { get; set; }
        public string IsConsultant { get; set; }
        public string PIN { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual mda mda { get; set; }
    }
}
