//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asset()
        {
            this.assessmenttables = new HashSet<assessmenttable>();
        }
    
        public int Asset_ID { get; set; }
        public string AssetName { get; set; }
        public string ImagePath { get; set; }
        public string AssetType { get; set; }
        public Nullable<int> TaxPayer { get; set; }
        public string LGA { get; set; }
        public Nullable<int> CompanyName { get; set; }
        public string IGR_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessmenttable> assessmenttables { get; set; }
        public virtual taxpayer taxpayer1 { get; set; }
        public virtual igr igr { get; set; }
        public virtual mda mda { get; set; }
        public virtual taxpayer taxpayer2 { get; set; }
    }
}
