//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiary
    {
        public string Benefuciary_ID { get; set; }
        public string MDA_ID { get; set; }
        public string Account_Number { get; set; }
        public string AccountName { get; set; }
        public string BankID { get; set; }
        public string Narration { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual mda mda { get; set; }
    }
}
