//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class buypowernotification
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Amount { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string SessionID { get; set; }
        public string BillerID { get; set; }
        public string BillerName { get; set; }
        public string ProductName { get; set; }
        public string SourceBankCode { get; set; }
        public string ProductID { get; set; }
        public string DestinationBankCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string meterNumber { get; set; }
        public string discoCode { get; set; }
        public string Token { get; set; }
        public string vendRef { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
