//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class colortab
    {
        public int ID { get; set; }
        public string ColourName { get; set; }
        public string Colour { get; set; }
        public string AscentColour { get; set; }
    }
}
