//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class enumeration
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string Region { get; set; }
        public string Enumerator { get; set; }
        public string PhoneNumber { get; set; }
        public string FeederName { get; set; }
        public string TransformerName { get; set; }
        public string TransfermerCode { get; set; }
        public string PoleServiceWireRemark { get; set; }
        public string PoleType { get; set; }
        public string PoleCondition { get; set; }
        public string WireType { get; set; }
        public string WireCondition { get; set; }
        public string PropertyType { get; set; }
        public string AccountNumber { get; set; }
        public string MeterTariff { get; set; }
        public string CustomerName { get; set; }
        public string CspName { get; set; }
        public string MeterNumber { get; set; }
        public string ServiceAddress { get; set; }
        public string CustomerTitle { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string HouseNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Street { get; set; }
        public string Email { get; set; }
        public string LandMark { get; set; }
        public string City { get; set; }
        public string Village { get; set; }
        public string CustomerStatus { get; set; }
        public string FileMeterNumber { get; set; }
        public string Lga { get; set; }
        public string CustormerRemark { get; set; }
        public string State { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public Nullable<double> Altitude { get; set; }
        public string AccountStatus { get; set; }
        public string BookCode { get; set; }
        public string AmountBilled { get; set; }
        public string MeterType { get; set; }
        public string MeterModel { get; set; }
        public string MeterStatus { get; set; }
        public string MeterPhase { get; set; }
        public string MeterRemark { get; set; }
        public string Date { get; set; }
        public System.DateTime created_at { get; set; }
        public string ImageId { get; set; }
        public string UniqueID { get; set; }
    }
}
