//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class fundsweep
    {
        public int Id { get; set; }
        public string Coll { get; set; }
        public string SerialNo { get; set; }
        public string AccountNo { get; set; }
        public string SortCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TxnDate { get; set; }
        public string Payee { get; set; }
        public string Payer { get; set; }
        public string Narration { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> AmountCollected { get; set; }
        public Nullable<decimal> AmountRemitted { get; set; }
        public Nullable<decimal> AgencyAmount { get; set; }
        public string Agency { get; set; }
        public string Status { get; set; }
        public string UploadId { get; set; }
        public string BillerID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> RemittedAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
