//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class igr_users
    {
        public string id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string PhoneNumber { get; set; }
        public string PIN { get; set; }
        public string Role { get; set; }
        public string Priviledges { get; set; }
        public string RoleId { get; set; }
        public string IGRCode { get; set; }
        public string IGR_Name { get; set; }
        public string MDACode { get; set; }
        public string MDA_Name { get; set; }
        public string MDAStation_Name { get; set; }
        public int CollectionLimit { get; set; }
    }
}
