//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public string invoice_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string MDA_ID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string MDAStation_ID { get; set; }
        public string USER_ID { get; set; }
        public string POS_ID { get; set; }
        public string SubHead_ID { get; set; }
        public string Type { get; set; }
        public string Invoice_Status { get; set; }
        public string AdmissionNo { get; set; }
        public string IGR_Code { get; set; }
    }
}
