//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class isnotification
    {
        public int Id { get; set; }
        public string ServiceUrl { get; set; }
        public string ServiceUsername { get; set; }
        public string ServicePassword { get; set; }
        public string FTPUrl { get; set; }
        public string FTPUsername { get; set; }
        public string FTPPassword { get; set; }
        public Nullable<bool> IsRepeated { get; set; }
        public string ProductGroupCode { get; set; }
        public string PaymentLogId { get; set; }
        public string CustReference { get; set; }
        public string AlternateCustReference { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentReference { get; set; }
        public string TerminalId { get; set; }
        public string ChannelName { get; set; }
        public string Location { get; set; }
        public Nullable<bool> IsReversal { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string InstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public string BranchName { get; set; }
        public string BankName { get; set; }
        public string FeeName { get; set; }
        public string CustomerName { get; set; }
        public string OtherCustomerInfo { get; set; }
        public string ReceiptNo { get; set; }
        public string CollectionsAccount { get; set; }
        public string ThirdPartyCode { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public string LeadBankCode { get; set; }
        public string LeadBankCbnCode { get; set; }
        public string LeadBankName { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string ItemQuantity { get; set; }
        public string BankCode { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string DepositorName { get; set; }
        public string DepositorSlipNumber { get; set; }
        public string PaymentCurrency { get; set; }
        public string OriginalPaymentLogId { get; set; }
        public string OriginalPaymentReference { get; set; }
        public string Teller { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> IsSent { get; set; }
    }
}
