//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class kedcopayment
    {
        public int Id { get; set; }
        public string TransactionId { get; set; }
        public string UserId { get; set; }
        public string PosId { get; set; }
        public string SubHead_ID { get; set; }
        public string AccountNumber { get; set; }
        public string MeterType { get; set; }
        public string PaymentMode { get; set; }
        public string TranactionDate { get; set; }
        public string TransactionReference { get; set; }
        public string LastTransactionDate { get; set; }
        public string StationId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public string ReceiptNumber { get; set; }
        public string TransactionType { get; set; }
        public string CustomerArears { get; set; }
        public bool IsRemitted { get; set; }
        public string RemittanceId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string tariffCode { get; set; }
    }
}
