//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class kingscare
    {
        public long Id { get; set; }
        public string SessionID { get; set; }
        public string TransactionDate { get; set; }
        public string SourceBankName { get; set; }
        public string DestinationBankCode { get; set; }
        public string PupilsName { get; set; }
        public string Class { get; set; }
        public string Term { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PayersName { get; set; }
        public string PhoneNumber { get; set; }
        public string Duration { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
