//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int Id { get; set; }
        public string sessionID { get; set; }
        public string SourceBankCode { get; set; }
        public string DestinationBankCode { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string name { get; set; }
        public string IGR_Code { get; set; }
        public string MDA_ID { get; set; }
        public string SubHead_ID { get; set; }
        public string SourceBankName { get; set; }
        public string MDAStation_ID { get; set; }
        public string payerid { get; set; }
        public string address { get; set; }
        public string tin { get; set; }
        public string remittance_id { get; set; }
        public string invoice_id { get; set; }
        public string refcode { get; set; }
        public string productType { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
