//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class oneclickpayment
    {
        public long id { get; set; }
        public string SessionID { get; set; }
        public string PayerName { get; set; }
        public string PhoneNumber { get; set; }
        public string Disco { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string SourceBank { get; set; }
        public string DestinationBank { get; set; }
        public int IsSent { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public System.DateTime Created_At { get; set; }
        public string MeterNumber { get; set; }
        public decimal Amount { get; set; }
    }
}
