//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentnotification
    {
        public int Id { get; set; }
        public string SessionID { get; set; }
        public string RequestorID { get; set; }
        public string PayerPhoneNumber { get; set; }
        public string PayerName { get; set; }
        public string MerchantCode { get; set; }
        public string MerchantName { get; set; }
        public string MerchantPhoneNumber { get; set; }
        public string ReferenceCode { get; set; }
        public string Amount { get; set; }
        public string TransactionDate { get; set; }
        public string ResponseCode { get; set; }
        public string sent_status { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
