//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos
    {
        public string POS_ID { get; set; }
        public string POS_imei { get; set; }
        public string POS_Name { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<bool> Activation { get; set; }
        public string MDA_ID { get; set; }
        public string Station_ID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual mda mda { get; set; }
        public virtual mda_stations mda_stations { get; set; }
    }
}
