//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class power
    {
        public int Id { get; set; }
        public string SourceBankCode { get; set; }
        public string SourceBankName { get; set; }
        public string InstitutionCode { get; set; }
        public int ChannelCode { get; set; }
        public int Step { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAccountNumber { get; set; }
        public string BillerID { get; set; }
        public string BillerName { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string Amount { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
    }
}
