//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportsparameter
    {
        public int ReportParameterID { get; set; }
        public string ReportID { get; set; }
        public string ReportParameterName { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> ShowParameter { get; set; }
    
        public virtual reportslisting reportslisting { get; set; }
    }
}
