//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenuehead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public revenuehead()
        {
            this.subheads = new HashSet<subhead>();
        }
    
        public string ID { get; set; }
        public string RevenueCode { get; set; }
        public string Biller_ID { get; set; }
        public string MDA_ID { get; set; }
        public string RevenueName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Taxable { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AssmentItem { get; set; }
        public string IsPOS { get; set; }
    
        public virtual igr igr { get; set; }
        public virtual mda mda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subhead> subheads { get; set; }
    }
}
