//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class richfield
    {
        public int Id { get; set; }
        public string SessionID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleType { get; set; }
        public string ProductType { get; set; }
        public string amount { get; set; }
        public string state { get; set; }
        public string DestinationBankCode { get; set; }
        public string SourceBankName { get; set; }
        public string TransactionDate { get; set; }
        public System.DateTime create_at { get; set; }
    }
}
