//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class rssh_upload
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Teller { get; set; }
        public string InvoiceDate { get; set; }
        public string Department { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public string UploadID { get; set; }
    }
}
