//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class schooldetail
    {
        public int Id { get; set; }
        public string AdmissionNo { get; set; }
        public string StudentName { get; set; }
        public string Class { get; set; }
        public string Term { get; set; }
        public string Session { get; set; }
        public string D_B { get; set; }
        public Nullable<decimal> SchoolFees { get; set; }
        public string Rebait { get; set; }
        public string remark { get; set; }
        public string BillerId { get; set; }
        public System.DateTime Created_At { get; set; }
        public string uploadId { get; set; }
    }
}
