//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class schoolnotification
    {
        public int Id { get; set; }
        public string SessionId { get; set; }
        public string BillerId { get; set; }
        public string SourceBank { get; set; }
        public string DestinationBank { get; set; }
        public string PayerName { get; set; }
        public string PayerPhone { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Email { get; set; }
        public string StudentName { get; set; }
        public string AdmissionNo { get; set; }
        public string Class { get; set; }
        public string Term { get; set; }
        public string Session { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
    }
}
