//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class schoolclass
    {
        public int Id { get; set; }
        public string ClassId { get; set; }
        public string IGR_Code { get; set; }
        public string ClassName { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public decimal SchoolFees { get; set; }
    }
}
