//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_information
    {
        public int Id { get; set; }
        public string IGR_Code { get; set; }
        public string AdmissionNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ClassId { get; set; }
        public string TermId { get; set; }
        public string SessionId { get; set; }
        public string StudentType { get; set; }
        public string Rebate { get; set; }
        public string Remark { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string uploadId { get; set; }
    }
}
