//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class subhead
    {
        public string SubHead_ID { get; set; }
        public string SubHead_Code { get; set; }
        public string RevHead_ID { get; set; }
        public string SubHead_Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Government { get; set; }
        public Nullable<decimal> Agency { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<bool> Recurrent { get; set; }
    
        public virtual revenuehead revenuehead { get; set; }
    }
}
