//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class tin
    {
        public string tin_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string IGR_Code { get; set; }
        public string tin_no { get; set; }
        public string temporary_tin { get; set; }
        public string phone { get; set; }
        public string nationality { get; set; }
        public string identification { get; set; }
        public string bussiness_type { get; set; }
        public string bussinesss_name { get; set; }
        public string bussiness_address { get; set; }
        public string bussiness_no { get; set; }
        public string reg_bus_name { get; set; }
        public Nullable<System.DateTime> commencement_date { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
