//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class valueswitchpayment
    {
        public long id { get; set; }
        public string SessionID { get; set; }
        public string CustomerName { get; set; }
        public string SourceBank { get; set; }
        public string DestinationBank { get; set; }
        public string BillerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BillerName { get; set; }
        public string CollectRef { get; set; }
        public string Narration { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int IsSent { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public System.DateTime Created_At { get; set; }
        public string CollectionTitle { get; set; }
        public string CollectionType { get; set; }
    }
}
