//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_collections
    {
        public string Collection_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string subhead_ID { get; set; }
        public string MDAStation_ID { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string MDAStation_Name { get; set; }
        public string pos_ID { get; set; }
        public string MDA_ID { get; set; }
        public long collectionType { get; set; }
        public long CollectionStatus { get; set; }
        public string User_ID { get; set; }
        public string SubHead_Name { get; set; }
        public string SubHead_Code { get; set; }
        public string RevenueCode { get; set; }
        public string RevenueName { get; set; }
        public string Biller_ID { get; set; }
        public string RevenueHead_ID { get; set; }
        public string Remittance_id { get; set; }
        public string MDA_Name { get; set; }
        public string Name { get; set; }
    }
}
