//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_remittances
    {
        public string Remittance_id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string MDAStation_ID { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string MDAStation_Name { get; set; }
        public string pos_ID { get; set; }
        public string MDA_ID { get; set; }
        public string MDA_Name { get; set; }
        public string Biller_ID { get; set; }
        public string User_ID { get; set; }
        public string remittance_status { get; set; }
        public string UserName { get; set; }
        public string channel { get; set; }
    }
}
