//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_collection
    {
        public string COLLECTION_ID { get; set; }
        public decimal Amount { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public string USER_ID { get; set; }
        public string remittance_id { get; set; }
        public string MDA_ID { get; set; }
        public string MDAStation_ID { get; set; }
        public string SubHead_ID { get; set; }
        public string POS_ID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int CollectionType { get; set; }
        public int CollectionStatus { get; set; }
        public long Id { get; set; }
    }
}
